// Generated by CoffeeScript 1.6.3
(function() {
  var canvas, ctx;

  canvas = document.getElementById('canvas');

  ctx = canvas.getContext("2d");

  ctx.beginPath();

  ctx.moveTo(100, 150);

  ctx.lineTo(300, 20);

  ctx.stroke();

}).call(this);
