// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    return $(document).keydown(function(e) {
      var direction;
      direction = {};
      switch (e.keyCode) {
        case 37:
          direction = {
            forward: 1,
            turn: -1
          };
          break;
        case 38:
          direction = {
            forward: 1
          };
          break;
        case 39:
          direction = {
            forward: 1,
            turn: 1
          };
          break;
        case 40:
          direction = {
            forward: -1
          };
          break;
        case 65:
          direction = {
            strafe: -1
          };
          break;
        case 68:
          direction = {
            strafe: 1
          };
      }
      return $.ajax("http://127.0.0.1:8071/motion-control/update", {
        data: direction,
        dataType: "jsonp"
      });
    });
  });

}).call(this);
